version: "3.3"

services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - discovery

  rabbitmq:
    image: "rabbitmq:3"

  redis:
    image: "redis:latest"

  discovery:
    image: "consul:1.8"
    ports:
      - "8500:8500" #Should not be in final
    environment:
      - CONSUL_LOCAL_CONFIG={"log_level":"info"}

  postgres-auth:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  trips-postgres:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  booking-postgres:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  trips:
    build:
      context: ./trips
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - rabbitmq
      - trips-postgres

  booking_1:
    build:
      context: ./booking
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - rabbitmq
      - booking-postgres

  booking_2:
    build:
      context: ./booking
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - rabbitmq
      - booking-postgres

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - postgres-auth
      - discovery
      - api-gateway
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile