spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth
          uri: http://auth:8080
          predicates:
            - Path=/api/auth/**
        - id: Trips
          uri: lb://trips
          predicates:
            - Path=/api/trips/**
        - id: Booking
          uri: lb://booking
          predicates:
            - Path=/api/booking/**
        - id: frontend
          uri: http://frontend:80
          predicates:
            - Path=/**