spring:
  application:
    name: booking
  datasource:
    url: "jdbc:postgresql://booking-postgres:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: rabbitmq
  mvc:
    throw-exception-if-no-handler-found: true
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}

tripServiceAddress: "trips:8080"